#ifndef STANDARD_ENUMS
#define STANDARD_ENUMS

// Fans controller
#define FANS_NOFAN 0
#define FANS_25KHZPWM 1
#define FANS_CUSTOM 99

// Matrix layouts
#define MATRIX_LEFTTORIGHT 0
#define MATRIX_SERPENTINE 1
#define MATRIX_REVERSESERPENTINE 2

// Device types
#define DEVICETYPE_UNSPECIFIED 0
#define DEVICETYPE_LEDS 1
#define DEVICETYPE_LEDS_PLUS_VOCORE 2
#define DEVICETYPE_LEDS_PLUS_USBD480 3
#define DEVICETYPE_LEDS_PLUS_MONITOR 4

#define DEVICETYPE_MATRIX 11
#define DEVICETYPE_MATRIX_PLUS_LEDS 12

#define DEVICETYPE_FANS 21

#endif
