#ifndef EXTERNAL_DEFINES
#define EXTERNAL_DEFINES
#endif

#define ENABLE_UPLOAD_PROTECTION 0
#define UPLOAD_AVAILABLE_DELAY 15000

#define DEVICE_AUTODETECT_ALLOWED 1
#define DEVICE_TYPE DEVICETYPE_LEDS
#define DEVICE_BRAND ""
#define DEVICE_NAME "My device"
#define DEVICE_VID 0x2e8a
#define DEVICE_PID 0xffff
#define DEVICE_PICTURE_URL "https://simhubdash.com/devices/nopicture.png"

#define STRIP1_RGBLEDCOUNT 8
#define STRIP1_DATAPIN 6
#define STRIP1_RIGHTTOLEFT 0
#define STRIP1_TYPE NEOPIXEL
#define STRIP1_MAX_BRIGHTNESS 255

#define STRIP2_RGBLEDCOUNT 0
#define STRIP2_DATAPIN 0
#define STRIP2_RIGHTTOLEFT 0
#define STRIP2_TYPE NEOPIXEL
#define STRIP2_MAX_BRIGHTNESS 255

#define STRIP3_RGBLEDCOUNT 0
#define STRIP3_DATAPIN 0
#define STRIP3_RIGHTTOLEFT 0
#define STRIP3_TYPE NEOPIXEL
#define STRIP3_MAX_BRIGHTNESS 255

#define STRIP4_RGBLEDCOUNT 0
#define STRIP4_DATAPIN 0
#define STRIP4_RIGHTTOLEFT 0
#define STRIP4_TYPE NEOPIXEL
#define STRIP4_MAX_BRIGHTNESS 255

#define LEDS_LAYOUT ""
#define DEFAULT_BUTTONS_COLORS ""
#define MATRIX_ENABLED 0
#define MATRIX_ROTATION 0
#define MATRIX_DATAPIN 6
#define MATRIX_LAYOUT MATRIX_LEFTTORIGHT
#define MATRIX_MAX_BRIGHTNESS 255

#define FANS_CONTROLLER FANS_NOFAN

#define PWMFANS_COUNT 0

#define PWMFANS_PIN_O1 9
#define PWMFANS_MIN_OUTPUT_O1 0
#define PWMFANS_MAX_OUTPUT_O1 1023
#define PWMFANS_RELAY_PIN_01 -1
#define PWMFANS_RELAY_DELAY_01 2000
#define PWMFANS_RELAY_REVERSELOGIC_01 0

#define PWMFANS_PIN_O2 -1
#define PWMFANS_MIN_OUTPUT_O2 0
#define PWMFANS_MAX_OUTPUT_O2 1023
#define PWMFANS_RELAY_PIN_02 -1
#define PWMFANS_RELAY_DELAY_02 2000
#define PWMFANS_RELAY_REVERSELOGIC_02 0

#define PWMFANS_PIN_O3 -1
#define PWMFANS_MIN_OUTPUT_O3 0
#define PWMFANS_MAX_OUTPUT_O3 1023
#define PWMFANS_RELAY_PIN_03 -1
#define PWMFANS_RELAY_DELAY_03 2000
#define PWMFANS_RELAY_REVERSELOGIC_03 0

